Bump com.nimbusds:nimbus-jose-jwt from 9.40 to 10.0.2 (#894)
Bumps
[com.nimbusds:nimbus-jose-jwt](https://bitbucket.org/connect2id/nimbus-jose-jwt)
from 9.40 to 10.0.2.
<details>
<summary>Changelog</summary>
<p><em>Sourced from <a
href="https://bitbucket.org/connect2id/nimbus-jose-jwt/src/master/CHANGELOG.txt">com.nimbusds:nimbus-jose-jwt's
changelog</a>.</em></p>
<blockquote>
<p>10.0.2 (2025-02-25)
* Updates JSONObjectUtils.parse and JSONArrayUtils.parse to reject JSON
strings with object and array nesting deeper than 255. This is intended
to prevent StackOverflowError's in Gson when a parsed JSON string with
excessive nesting is serialised, for example to log the claims of a
parsed JWT. Note that in Gson the JSON reader is not susceptible to
StackOverflowError's, only the serialisation. The nesting limit of depth
255 is introduced in Gson 2.12.0 (iss <a
href="https://bitbucket.org/connect2id/nimbus-jose-jwt/issues/583">#583</a>).
* Updates GSon to 2.12.1.</p>
<p>10.1 (2025-04-03)
* Restores module-info.java.
* Adds ExpiredJWTException extends BadJWTException to enable easy
programmatic detection whether a JWT has expired (iss <a
href="https://bitbucket.org/connect2id/nimbus-jose-jwt/issues/585">#585</a>).
* Adds URLBasedJWKSetSource getJWKSetURL and getResourceRetriever
methods
to ease class extension.</p>
<p>10.2 (2025-04-07)
* Gson is made a direct instead of a shaded dependency to address module
issues introduced in 10.1 (iss <a
href="https://bitbucket.org/connect2id/nimbus-jose-jwt/issues/550">#550</a>).</p>
<p>10.3 (2025-05-09)
* Restores the Gson shading, adding placeholder interfaces to prevent
NoClassDefFoundError occurrences at runtime when the JAR is used on a
module path (iss <a
href="https://bitbucket.org/connect2id/nimbus-jose-jwt/issues/550">#550</a>).</p>
<p>10.3.1 (2025-07-01)
* OctetKeyPairGenerator with Curve.Ed25519 should use the provided
SecureRandom (iss <a
href="https://bitbucket.org/connect2id/nimbus-jose-jwt/issues/590">#590</a>).</p>
</blockquote>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a
href="https://bitbucket.org/connect2id/nimbus-jose-jwt/commits/418595bdaff73a9618fe2862ac246340cba77a88"><code>418595b</code></a>
[maven-release-plugin] prepare for next development iteration</li>
<li><a
href="https://bitbucket.org/connect2id/nimbus-jose-jwt/commits/1923b4f36186df35fe38014304c5205637aaca58"><code>1923b4f</code></a>
Adds JWKParameterNames.PUBLIC constant</li>
<li><a
href="https://bitbucket.org/connect2id/nimbus-jose-jwt/commits/ec090bd7c8434721b8a065c9784effb341b0ef7c"><code>ec090bd</code></a>
[maven-release-plugin] prepare release 9.46</li>
<li><a
href="https://bitbucket.org/connect2id/nimbus-jose-jwt/commits/5ae16148b202fd92b72da29b0bcd3f00c526d8a4"><code>5ae1614</code></a>
[maven-release-plugin] prepare for next development iteration</li>
<li><a
href="https://bitbucket.org/connect2id/nimbus-jose-jwt/commits/10b13c99cb12907f9e717b17f140196318d80e79"><code>10b13c9</code></a>
Replaces unreachable else in AESEncrypter with assertion</li>
<li><a
href="https://bitbucket.org/connect2id/nimbus-jose-jwt/commits/72275bc7722272f80a00f7115613a0a7fd7cff93"><code>72275bc</code></a>
Adds static JSONArrayUtils.parse(String),
JSONArrayUtils.toJSONString(List&lt;?&gt;)</li>
<li><a
href="https://bitbucket.org/connect2id/nimbus-jose-jwt/commits/55e7dc41337a2aa552c61f4b7e4f9fc8f0dd1177"><code>55e7dc4</code></a>
JSONObjectUtils.toJSONString must throw NPE on null String (iss <a
href="https://bitbucket.org/connect2id/nimbus-jose-jwt/issues/577">#577</a>)</li>
<li><a
href="https://bitbucket.org/connect2id/nimbus-jose-jwt/commits/ed736420a6d0cda474a9054ccb3482b02f67ea40"><code>ed73642</code></a>
Fixes regression: Invalid JSON was accepted in versions 9.24+ (iss <a
href="https://bitbucket.org/connect2id/nimbus-jose-jwt/issues/574">#574</a>)</li>
<li><a
href="https://bitbucket.org/connect2id/nimbus-jose-jwt/commits/8eb6fbd496bd2817d94c54780a7bdb56fb60840c"><code>8eb6fbd</code></a>
[maven-release-plugin] prepare release 9.47</li>
<li><a
href="https://bitbucket.org/connect2id/nimbus-jose-jwt/commits/6020cd17c747bf7bc7d3f6a022daacec2fa52344"><code>6020cd1</code></a>
[maven-release-plugin] prepare for next development iteration</li>
<li>Additional commits viewable in <a
href="https://bitbucket.org/connect2id/nimbus-jose-jwt/branches/compare/10.0.2..9.40">compare
view</a></li>
</ul>
</details>
<br />


[![Dependabot compatibility
score](https://dependabot-badges.githubapp.com/badges/compatibility_score?dependency-name=com.nimbusds:nimbus-jose-jwt&package-manager=maven&previous-version=9.40&new-version=10.0.2)](https://docs.github.com/en/github/managing-security-vulnerabilities/about-dependabot-security-updates#about-compatibility-scores)

Dependabot will resolve any conflicts with this PR as long as you don't
alter it yourself. You can also trigger a rebase manually by commenting
`@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits
that have been made to it
- `@dependabot merge` will merge this PR after your CI passes on it
- `@dependabot squash and merge` will squash and merge this PR after
your CI passes on it
- `@dependabot cancel merge` will cancel a previously requested merge
and block automerging
- `@dependabot reopen` will reopen this PR if it is closed
- `@dependabot close` will close this PR and stop Dependabot recreating
it. You can achieve the same result by closing it manually
- `@dependabot show <dependency name> ignore conditions` will show all
of the ignore conditions of the specified dependency
- `@dependabot ignore this major version` will close this PR and stop
Dependabot creating any more for this major version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this minor version` will close this PR and stop
Dependabot creating any more for this minor version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this dependency` will close this PR and stop
Dependabot creating any more for this dependency (unless you reopen the
PR or upgrade to it yourself)
You can disable automated security fix PRs for this repo from the
[Security Alerts
page](https://github.com/databricks/databricks-jdbc/network/alerts).

</details>

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>